"""
###########################################################
# Developer: Arun Goyal (B911959)                         #
#                                                         #
# Filename: Task1.py                                      #
# Description: Validation of the imported AES library     #
#      using the keys and messages specified in the brief #
#                                                         #
# Dependencies: aes                                       #
###########################################################
"""

import aes

# Encode text strings as UTF8
ENCODING = "utf8"

# Formatting the encryption key and instantiating the imported AES object
# AES object explicitly set to ECB mode
key = "i like to party "[::-1]
encoded_key = aes.utils.bytes2int(bytes(key, ENCODING))
Cipher = aes.aes(encoded_key, 128, mode="ECB")

# Formatting and encryption of validation string
message = "I like to joggin"[::-1]
encoded_message = aes.utils.int2arr8bit(aes.utils.bytes2int(bytes(message, ENCODING)), 16)
ciphertext = Cipher.enc_once(encoded_message)

# Decryption of ciphertext and decoding into string
plaintext = Cipher.dec_once(ciphertext)
decoded_plaintext = "".join([chr(x) for x in plaintext])

# Output all values generated by process to stdout
print("-"*30 + " Task 1 Output " + "-"*30)
print(f"Initialisation Vector: None")
print(f"Key String: {key[::-1]}")
print(f"Encoded Key: {aes.utils.int2arr8bit(encoded_key, 16)}")
print()
print(f"Message String: {message[::-1]}")
print(f"Encoded Message: {encoded_message}")
print(f"Ciphertext: {ciphertext}")
print()
print(f"Decrypted Plaintext: {plaintext}")
print(f"Decoded Plaintext: {decoded_plaintext}")
